### PR TITLE
Merge and fix broken tests

### PR DESCRIPTION
**Pull request by fvlima**
Merge with master of jazzband/django-oauth-toolkit and fix brokens tests about missing attributes in migrations tests

### CODE REVIEW

**Comment by wiliamsouza** [comment]
@fvlima Conflicts must be resolved.
Todo do so just follow the  mini how to git rebase bellow:
```
git clone https://github.com/wiliamsouza/django-oauth-toolkit.git
cd django-oauth-toolkit
git checkout -b openid-connect origin/openid-connect
git rebase master
```
Keep resolving conflicts and run `git rebase --continue` until the rebase finish.
After that just create a new branch `git checkout -b my-new-branch`.
Add your new code.
Open a pull request.

Doing this way you keep the history and commits correct.

**Comment by fvlima** [comment]
I don't know what mistakes I did, but all conflicts were resolved locally with rebase, just like it. I will see it again today night

**Comment by fvlima** [comment]
I don't know what mistakes I did, but all conflicts were resolved locally. I will see it again today night

**Comment by fvlima** [comment]
So, I did the same again just to confirm what I did before, and the conflicts are the same when trying to open the PR:

image

The merges with rebase were done, and a new commit created to fix the missing attributes on test migration.

**Comment by fvlima** [comment]
I opened another https://github.com/wiliamsouza/django-oauth-toolkit/pull/7. When you can, see it please. As I said before, after rebase with master, it's necessary to rebase (or pull) with remote `openid-connect`, because if I don't do that, the conflicts continue when try to open the PR and associate with this branch

**Pull request closed without merging**
